#!/bin/bash

BUILD_DATE=`date '+%Y%m%d'`
IMAGE_TAG=`git describe --tags --dirty --always`
BASE_IMAGE_TAG=`cat ./tools/base-image-tag | sed -e 's/^[[:space:]]*//'`

sha1sum -c ./pnpm-lock.yaml.sha1
if [ $? == 0 ]; then
  echo 'pnpm-lock file not changed'
else
  echo 'pnpm-lock file changed'
  sha1sum ./pnpm-lock.yaml > ./pnpm-lock.yaml.sha1

  echo $IMAGE_TAG > ./tools/base-image-tag
  BASE_IMAGE_TAG=$IMAGE_TAG

  docker build -f ./tools/builder-image.Dockerfile -t qps-web-builder:${BASE_IMAGE_TAG} .
  docker build -f ./tools/runner-image.Dockerfile -t qps-web-runner:${BASE_IMAGE_TAG} .
fi

docker build \
  --build-arg BASE_IMAGE_TAG=${BASE_IMAGE_TAG} \
  -f ./tools/production-image.Dockerfile \
  -t qps-web:${BUILD_DATE}-${IMAGE_TAG} .

docker tag qps-web:${BUILD_DATE}-${IMAGE_TAG} qps-web:latest
